module.exports = [
  {
    date: "Oct 17, 2023",
    time: "7pm",
    complete: true,
    team1_name: "Duck Island Saints",
    team1_team_id: 2,
    team1_score: 7,
    team1_result: "win",
    team2_name: "Mighty Moose",
    team2_team_id: 3,
    team2_score: 5,
    team2_result: "loss",
  },
  {
    date: "Oct 17, 2023",
    time: "8pm",
    complete: true,
    team1_name: "Fogtown Leprechauns",
    team1_team_id: 1,
    team1_score: 9,
    team1_result: "loss",
    team2_name: "Kraken Beers",
    team2_team_id: 4,
    team2_score: 11,
    team2_result: "win",
  },
  {
    date: "Oct 24, 2023",
    time: "9pm",
    complete: true,
    team1_name: "Fogtown Leprechauns",
    team1_team_id: 1,
    team1_score: 10,
    team1_result: "loss",
    team2_name: "Mighty Moose",
    team2_team_id: 3,
    team2_score: 15,
    team2_result: "win",
  },
  {
    date: "Oct 24, 2023",
    time: "10pm",
    complete: true,
    team1_name: "Duck Island Saints",
    team1_team_id: 2,
    team1_score: 5,
    team1_result: "loss",
    team2_name: "Kraken Beers",
    team2_team_id: 4,
    team2_score: 16,
    team2_result: "win",
  },
  {
    date: "Oct 31, 2023",
    time: "9pm",
    complete: true,
    team1_name: "Duck Island Saints",
    team1_team_id: 2,
    team1_score: 2,
    team1_result: "loss",
    team2_name: "Kraken Beers",
    team2_team_id: 4,
    team2_score: 11,
    team2_result: "win",
  },
  {
    date: "Oct 31, 2023",
    time: "10pm",
    complete: true,
    team1_name: "Fogtown Leprechauns",
    team1_team_id: 1,
    team1_score: 12,
    team1_result: "tie",
    team2_name: "Mighty Moose",
    team2_team_id: 3,
    team2_score: 12,
    team2_result: "tie",
  },
  {
    date: "Nov 7, 2023",
    time: "9pm",
    complete: true,
    team1_name: "Mighty Moose",
    team1_team_id: 3,
    team1_score: 10,
    team1_result: "win",
    team2_name: "Kraken Beers",
    team2_team_id: 4,
    team2_score: 8,
    team2_result: "loss",
  },
  {
    date: "Nov 7, 2023",
    time: "10pm",
    complete: true,
    team1_name: "Duck Island Saints",
    team1_team_id: 2,
    team1_score: 9,
    team1_result: "win",
    team2_name: "Fogtown Leprechauns",
    team2_team_id: 1,
    team2_score: 7,
    team2_result: "loss",
  },
  {
    date: "Nov 14, 2023",
    time: "9pm",
    complete: true,
    team1_name: "Fogtown Leprechauns",
    team1_team_id: 1,
    team1_score: 9,
    team1_result: "loss",
    team2_name: "Kraken Beers",
    team2_team_id: 4,
    team2_score: 13,
    team2_result: "win",
  },
  {
    date: "Nov 14, 2023",
    time: "10pm",
    complete: true,
    team1_name: "Duck Island Saints",
    team1_team_id: 2,
    team1_score: 8,
    team1_result: "win",
    team2_name: "Mighty Moose",
    team2_team_id: 3,
    team2_score: 5,
    team2_result: "loss",
  },
  {
    date: "Nov 21, 2023",
    time: "9pm",
    complete: true,
    team1_name: "Duck Island Saints",
    team1_team_id: 2,
    team1_score: 5,
    team1_result: "win",
    team2_name: "Fogtown Leprechauns",
    team2_team_id: 1,
    team2_score: 4,
    team2_result: "loss",
  },
  {
    date: "Nov 21, 2023",
    time: "10pm",
    complete: true,
    team1_name: "Kraken Beers",
    team1_team_id: 4,
    team1_score: 10,
    team1_result: "tie",
    team2_name: "Mighty Moose",
    team2_team_id: 3,
    team2_score: 10,
    team2_result: "tie",
  },
  {
    date: "Nov 28, 2023",
    time: "9pm",
    complete: true,
    team1_name: "Fogtown Leprechauns",
    team1_team_id: 1,
    team1_score: 8,
    team1_result: "loss",
    team2_name: "Mighty Moose",
    team2_team_id: 3,
    team2_score: 10,
    team2_result: "win",
  },
  {
    date: "Nov 28, 2023",
    time: "10pm",
    complete: true,
    team1_name: "Kraken Beers",
    team1_team_id: 4,
    team1_score: 5,
    team1_result: "loss",
    team2_name: "Duck Island Saints",
    team2_team_id: 2,
    team2_score: 10,
    team2_result: "win",
  },
  {
    date: "Dec 5, 2023",
    time: "9pm",
    complete: true,
    team1_name: "Duck Island Saints",
    team1_team_id: 2,
    team1_score: 7,
    team1_result: "loss",
    team2_name: "Mighty Moose",
    team2_team_id: 3,
    team2_score: 11,
    team2_result: "win",
  },
  {
    date: "Dec 5, 2023",
    time: "10pm",
    complete: true,
    team1_name: "Fogtown Leprechauns",
    team1_team_id: 1,
    team1_score: 7,
    team1_result: "loss",
    team2_name: "Mighty Moose",
    team2_team_id: 3,
    team2_score: 12,
    team2_result: "win",
  },
  {
    date: "Dec 12, 2023",
    time: "9pm",
    complete: true,
    team1_name: "Kraken Beers",
    team1_team_id: 4,
    team1_score: 4,
    team1_result: "loss",
    team2_name: "Mighty Moose",
    team2_team_id: 3,
    team2_score: 7,
    team2_result: "win",
  },
  {
    date: "Dec 12, 2023",
    time: "10pm",
    complete: true,
    team1_name: "Fogtown Leprechauns",
    team1_team_id: 1,
    team1_score: 11,
    team1_result: "win",
    team2_name: "Duck Island Saints",
    team2_team_id: 2,
    team2_score: 5,
    team2_result: "loss",
  },
  {
    date: "Dec 19, 2023",
    time: "9pm",
    complete: true,
    team1_name: "Fogtown Leprechauns",
    team1_team_id: 1,
    team1_score: 11,
    team1_result: "win",
    team2_name: "Mighty Moose",
    team2_team_id: 3,
    team2_score: 9,
    team2_result: "loss",
  },
  {
    date: "Dec 19, 2023",
    time: "10pm",
    complete: true,
    team1_name: "Kraken Beers",
    team1_team_id: 4,
    team1_score: 7,
    team1_result: "win",
    team2_name: "Duck Island Saints",
    team2_team_id: 2,
    team2_score: 5,
    team2_result: "loss",
  },
  {
    date: "Jan 2, 2024",
    time: "9pm",
    complete: true,
    team1_name: "Fogtown Leprechauns",
    team1_team_id: 1,
    team1_score: 14,
    team1_result: "loss",
    team2_name: "Mighty Moose",
    team2_team_id: 3,
    team2_score: 15,
    team2_result: "win",
  },
  {
    date: "Jan 2, 2024",
    time: "10pm",
    complete: true,
    team1_name: "Kraken Beers",
    team1_team_id: 4,
    team1_score: 9,
    team1_result: "loss",
    team2_name: "Duck Island Saints",
    team2_team_id: 2,
    team2_score: 14,
    team2_result: "win",
  },
  {
    date: "Jan 9, 2024",
    time: "9pm",
    complete: true,
    team1_name: "Fogtown Leprechauns",
    team1_team_id: 1,
    team1_score: 14,
    team1_result: "win",
    team2_name: "Duck Island Saints",
    team2_team_id: 2,
    team2_score: 11,
    team2_result: "loss",
  },
  {
    date: "Jan 9, 2024",
    time: "10pm",
    complete: true,
    team1_name: "Kraken Beers",
    team1_team_id: 4,
    team1_score: 7,
    team1_result: "loss",
    team2_name: "Mighty Moose",
    team2_team_id: 3,
    team2_score: 12,
    team2_result: "win",
  },
  {
    date: "Jan 16, 2024",
    time: "9pm",
    complete: true,
    team1_name: "Fogtown Leprechauns",
    team1_team_id: 1,
    team1_score: 11,
    team1_result: "loss",
    team2_name: "Kraken Beers",
    team2_team_id: 4,
    team2_score: 12,
    team2_result: "win",
  },
  {
    date: "Jan 16, 2024",
    time: "10pm",
    complete: true,
    team1_name: "Mighty Moose",
    team1_team_id: 3,
    team1_score: 13,
    team1_result: "win",
    team2_name: "Duck Island Saints",
    team2_team_id: 2,
    team2_score: 3,
    team2_result: "loss",
  },
  {
    date: "Jan 23, 2024",
    time: "9pm",
    complete: true,
    team1_name: "Mighty Moose",
    team1_team_id: 3,
    team1_score: 8,
    team1_result: "loss",
    team2_name: "Kraken Beers",
    team2_team_id: 4,
    team2_score: 9,
    team2_result: "win",
  },
  {
    date: "Jan 23, 2024",
    time: "10pm",
    complete: true,
    team1_name: "Fogtown Leprechauns",
    team1_team_id: 1,
    team1_score: 8,
    team1_result: "loss",
    team2_name: "Duck Island Saints",
    team2_team_id: 2,
    team2_score: 11,
    team2_result: "win",
  },
  {
    date: "Jan 30, 2024",
    time: "9pm",
    complete: true,
    team1_name: "Duck Island Saints",
    team1_team_id: 2,
    team1_score: 7,
    team1_result: "loss",
    team2_name: "Fogtown Leprechauns",
    team2_team_id: 1,
    team2_score: 8,
    team2_result: "win",
  },
  {
    date: "Jan 30, 2024",
    time: "10pm",
    complete: true,
    team1_name: "Kraken Beers",
    team1_team_id: 4,
    team1_score: 5,
    team1_result: "loss",
    team2_name: "Mighty Moose",
    team2_team_id: 3,
    team2_score: 11,
    team2_result: "win",
  },
  {
    date: "Feb 6, 2024",
    time: "9pm",
    complete: false,
    team1_name: "Fogtown Leprechauns",
    team1_team_id: 1,
    team1_score: null,
    team1_result: null,
    team2_name: "Mighty Moose",
    team2_team_id: 3,
    team2_score: null,
    team2_result: null,
  },
  {
    date: "Feb 6, 2024",
    time: "10pm",
    complete: false,
    team1_name: "Duck Island Saints",
    team1_team_id: 2,
    team1_score: null,
    team1_result: null,
    team2_name: "Kraken Beers",
    team2_team_id: 4,
    team2_score: null,
    team2_result: null,
  },
  {
    date: "Feb 13, 2024",
    time: "9pm",
    complete: false,
    team1_name: "Fogtown Leprechauns",
    team1_team_id: 1,
    team1_score: null,
    team1_result: null,
    team2_name: "Kraken Beers",
    team2_team_id: 4,
    team2_score: null,
    team2_result: null,
  },
  {
    date: "Feb 13, 2024",
    time: "10pm",
    complete: false,
    team1_name: "Duck Island Saints",
    team1_team_id: 2,
    team1_score: null,
    team1_result: null,
    team2_name: "Mighty Moose",
    team2_team_id: 3,
    team2_score: null,
    team2_result: null,
  },
  {
    date: "Feb 20, 2024",
    time: "9pm",
    complete: false,
    team1_name: "Mighty Moose",
    team1_team_id: 3,
    team1_score: null,
    team1_result: null,
    team2_name: "Kraken Beers",
    team2_team_id: 4,
    team2_score: null,
    team2_result: null,
  },
  {
    date: "Feb 20, 2024",
    time: "10pm",
    complete: false,
    team1_name: "Duck Island Saints",
    team1_team_id: 2,
    team1_score: null,
    team1_result: null,
    team2_name: "Fogtown Leprechauns",
    team2_team_id: 1,
    team2_score: null,
    team2_result: null,
  },
  {
    date: "Feb 27, 2024",
    time: "9pm",
    complete: false,
    team1_name: "Mighty Moose",
    team1_team_id: 3,
    team1_score: null,
    team1_result: null,
    team2_name: "Duck Island Saints",
    team2_team_id: 2,
    team2_score: null,
    team2_result: null,
  },
  {
    date: "Feb 27, 2024",
    time: "10pm",
    complete: false,
    team1_name: "Kraken Beers",
    team1_team_id: 4,
    team1_score: null,
    team1_result: null,
    team2_name: "Fogtown Leprechauns",
    team2_team_id: 1,
    team2_score: null,
    team2_result: null,
  },
  {
    date: "Mar 5, 2024",
    time: "9pm",
    complete: false,
    team1_name: "Fogtown Leprechauns",
    team1_team_id: 1,
    team1_score: null,
    team1_result: null,
    team2_name: "Duck Island Saints",
    team2_team_id: 2,
    team2_score: null,
    team2_result: null,
  },
  {
    date: "Mar 5, 2024",
    time: "10pm",
    complete: false,
    team1_name: "Mighty Moose",
    team1_team_id: 3,
    team1_score: null,
    team1_result: null,
    team2_name: "Kraken Beers",
    team2_team_id: 4,
    team2_score: null,
    team2_result: null,
  },
  {
    date: "Mar 12, 2024",
    time: "9pm",
    complete: false,
    team1_name: "Fogtown Leprechauns",
    team1_team_id: 1,
    team1_score: null,
    team1_result: null,
    team2_name: "Mighty Moose",
    team2_team_id: 3,
    team2_score: null,
    team2_result: null,
  },
  {
    date: "Mar 12, 2024",
    time: "10pm",
    complete: false,
    team1_name: "Duck Island Saints",
    team1_team_id: 2,
    team1_score: null,
    team1_result: null,
    team2_name: "Kraken Beers",
    team2_team_id: 4,
    team2_score: null,
    team2_result: null,
  },
];
