module.exports = [
  {
    name: "Alex Smeall (C)",
    team_id: 1,
    position: "D",
    number: 21,
  },
  {
    name: "Jason Duggan (A)",
    team_id: 1,
    position: "F",
    number: 10,
  },
  {
    name: "Grant Samson (A)",
    team_id: 1,
    position: "F",
    number: 11,
  },
  {
    name: "Josh Shears",
    team_id: 1,
    position: "F",
    number: 17,
  },
  {
    name: "Matthew Cheeks",
    team_id: 1,
    position: "F",
    number: 88,
  },
  {
    name: "Alan McDonald",
    team_id: 1,
    position: "F",
    number: 15,
  },
  {
    name: "Liam Henebury",
    team_id: 1,
    position: "D",
    number: 2,
  },
  {
    name: "Greg Abbott",
    team_id: 1,
    position: "D",
    number: 3,
  },
  {
    name: "Steven Brewer",
    team_id: 1,
    position: "D",
    number: 7,
  },
  {
    name: "Jamie Greeley",
    team_id: 1,
    position: "F",
    number: 96,
  },
  {
    name: "Philip Fowler",
    team_id: 1,
    position: "G",
    number: 35,
  },
  {
    name: "Christian O'Leary",
    team_id: 1,
    position: "F",
    number: 18,
  },
  {
    name: "Noah Payne",
    team_id: 1,
    position: "F",
    number: 8,
  },
  {
    name: "Austin St. Croix",
    team_id: 1,
    position: "F",
    number: 91,
  },
  {
    name: "Nick Tuck",
    team_id: 1,
    position: "D",
    number: 48,
  },
  {
    name: "Stephen Ford",
    team_id: 1,
    position: "F",
    number: null,
  },
  {
    name: "Rylan Bent",
    team_id: 1,
    position: "F",
    number: null,
  },
  {
    name: "Jared Butt",
    team_id: 1,
    position: "F",
    number: null,
  },
  {
    name: "Rob Padden",
    team_id: 1,
    position: "D",
    number: null,
  },
  {
    name: "Raymond Furlong",
    team_id: 1,
    position: "F",
    number: null,
  },
  {
    name: "Sean Tobin",
    team_id: 1,
    position: "G",
    number: null,
  },
  {
    name: "Nikkia Boutcher",
    team_id: 1,
    position: "G",
    number: null,
  },
  {
    name: "Greg Thorne",
    team_id: 1,
    position: "F",
    number: null,
  },
  {
    name: "Jeremiah Gill",
    team_id: 1,
    position: "F",
    number: null,
  },
  {
    name: "Tyler Byrne",
    team_id: 1,
    position: "F",
    number: null,
  },
  {
    name: "Leo Ford",
    team_id: 1,
    position: "F",
    number: null,
  },
  {
    name: "Ben Hillyard",
    team_id: 1,
    position: "F",
    number: null,
  },
  {
    name: "Drew Saunders (C)",
    team_id: 2,
    position: "F",
    number: 58,
  },
  {
    name: "Brady Miller (A)",
    team_id: 2,
    position: "F",
    number: 22,
  },
  {
    name: "Chris Brown",
    team_id: 2,
    position: "F",
    number: 11,
  },
  {
    name: "Joel James",
    team_id: 2,
    position: "F",
    number: 18,
  },
  {
    name: "Corey Normore",
    team_id: 2,
    position: "F",
    number: 3,
  },
  {
    name: "Dakota Summers",
    team_id: 2,
    position: "F",
    number: 28,
  },
  {
    name: "Josh Dillon",
    team_id: 2,
    position: "D",
    number: 10,
  },
  {
    name: "Noah Normore",
    team_id: 2,
    position: "D",
    number: 87,
  },
  {
    name: "Alex Vincent",
    team_id: 2,
    position: "D",
    number: 20,
  },
  {
    name: "Jeff Davis",
    team_id: 2,
    position: "F",
    number: null,
  },
  {
    name: "Nathan Bladen",
    team_id: 2,
    position: "F",
    number: null,
  },
  {
    name: "Devin Burt",
    team_id: 2,
    position: "F",
    number: null,
  },
  {
    name: "Bradley Fitzpatrick",
    team_id: 2,
    position: "F",
    number: null,
  },
  {
    name: "Aaron Neil",
    team_id: 2,
    position: "D",
    number: null,
  },
  {
    name: "Devon Beason",
    team_id: 2,
    position: "D",
    number: null,
  },
  {
    name: "Luke Quinlan",
    team_id: 2,
    position: "D",
    number: null,
  },
  {
    name: "Curtis Winters",
    team_id: 2,
    position: "G",
    number: 31,
  },
  {
    name: "Wilfred Butt",
    team_id: 2,
    position: "G",
    number: null,
  },
  {
    name: "Sean Tobin",
    team_id: 2,
    position: "G",
    number: null,
  },
  {
    name: "Nathan Bladen (C)",
    team_id: 3,
    position: "F",
    number: null,
  },
  {
    name: "Darren Noseworthy",
    team_id: 3,
    position: "F",
    number: 93,
  },
  {
    name: "Anthony Hill",
    team_id: 3,
    position: "F",
    number: 88,
  },
  {
    name: "Aaron Troy",
    team_id: 3,
    position: "F",
    number: 8,
  },
  {
    name: "Paddy Slaney",
    team_id: 3,
    position: "F",
    number: 11,
  },
  {
    name: "Tyler Walsh",
    team_id: 3,
    position: "D",
    number: 3,
  },
  {
    name: "Shane Carrigan",
    team_id: 3,
    position: "D",
    number: 14,
  },
  {
    name: "Murray Smith",
    team_id: 3,
    position: "D",
    number: 4,
  },
  {
    name: "Clayton Oldford",
    team_id: 3,
    position: "D",
    number: 5,
  },
  {
    name: "Kyle McBay",
    team_id: 3,
    position: "F",
    number: 19,
  },
  {
    name: "Darrin Hunt",
    team_id: 3,
    position: "D",
    number: 9,
  },
  {
    name: "Dustin Parsons",
    team_id: 3,
    position: "D",
    number: 2,
  },
  {
    name: "Carter Maughan",
    team_id: 3,
    position: "D",
    number: 19,
  },
  {
    name: "Nathan Hillier",
    team_id: 3,
    position: "D",
    number: 9,
  },
  {
    name: "Scott Mugford",
    team_id: 3,
    position: "D",
    number: 2,
  },
  {
    name: "Ryan Fifeild",
    team_id: 3,
    position: "F",
    number: null,
  },
  {
    name: "Ryan Slaney",
    team_id: 3,
    position: "",
    number: null,
  },
  {
    name: "Stephen Quigley",
    team_id: 3,
    position: "G",
    number: null,
  },
  {
    name: "Tomas Shea",
    team_id: 3,
    position: "G",
    number: null,
  },
  {
    name: "Jamie Ross",
    team_id: 3,
    position: "G",
    number: null,
  },
  {
    name: "Shane Stacey (C)",
    team_id: 4,
    position: "F",
    number: null,
  },
  {
    name: "Braden Skiffington",
    team_id: 4,
    position: "F",
    number: 9,
  },
  {
    name: "Mark Holloway",
    team_id: 4,
    position: "F",
    number: 14,
  },
  {
    name: "Nick Best",
    team_id: 4,
    position: "F",
    number: 22,
  },
  {
    name: "Josh Casey",
    team_id: 4,
    position: "F",
    number: 5,
  },
  {
    name: "Jack Hanlon",
    team_id: 4,
    position: "F",
    number: 8,
  },
  {
    name: "Mike Dwyer",
    team_id: 4,
    position: "D",
    number: 7,
  },
  {
    name: "Jarrett Walters",
    team_id: 4,
    position: "D",
    number: 7,
  },
  {
    name: "Chase Barrett",
    team_id: 4,
    position: "D",
    number: 4,
  },
  {
    name: "Nick Patey",
    team_id: 4,
    position: "D",
    number: 21,
  },
  {
    name: "Joey Toope",
    team_id: 4,
    position: "F",
    number: null,
  },
  {
    name: "Issiah Clowe",
    team_id: 4,
    position: "F",
    number: null,
  },
  {
    name: "Adam Martino",
    team_id: 4,
    position: "F",
    number: null,
  },
  {
    name: "Daniel Lucas",
    team_id: 4,
    position: "F",
    number: null,
  },
  {
    name: "Bailey Mercer",
    team_id: 4,
    position: "F",
    number: null,
  },
  {
    name: "Paul Durdle",
    team_id: 4,
    position: "F",
    number: null,
  },
  {
    name: "Coady Bungay",
    team_id: 4,
    position: "D",
    number: null,
  },
  {
    name: "Lucas Briffett",
    team_id: 4,
    position: "D",
    number: null,
  },
  {
    name: "Lucas Squibb",
    team_id: 4,
    position: "G",
    number: null,
  },
];
