module.exports = [
  {
    id: 1,
    game_id: 1,
    player_name: "Aaron Troy",
    player_id: 50,
    team_id: 3,
    goals: 0,
    assists: 0,
  },
  {
    id: 2,
    game_id: 1,
    player_name: "Anthony Hill",
    player_id: 49,
    team_id: 3,
    goals: 1,
    assists: 0,
  },
  {
    id: 3,
    game_id: 1,
    player_name: "Clayton Oldford",
    player_id: 55,
    team_id: 3,
    goals: 0,
    assists: 0,
  },
  {
    id: 4,
    game_id: 1,
    player_name: "Darren Noseworthy",
    player_id: 48,
    team_id: 3,
    goals: 1,
    assists: 0,
  },
  {
    id: 5,
    game_id: 1,
    player_name: "Murray Smith",
    player_id: 54,
    team_id: 3,
    goals: 0,
    assists: 0,
  },
  {
    id: 6,
    game_id: 1,
    player_name: "Paddy Slaney",
    player_id: 51,
    team_id: 3,
    goals: 2,
    assists: 0,
  },
  {
    id: 7,
    game_id: 1,
    player_name: "Shane Carrigan",
    player_id: 53,
    team_id: 3,
    goals: 0,
    assists: 0,
  },
  {
    id: 8,
    game_id: 1,
    player_name: "Tyler Walsh",
    player_id: 52,
    team_id: 3,
    goals: 0,
    assists: 0,
  },
  {
    id: 9,
    game_id: 1,
    player_name: "Carter Maughan",
    player_id: 59,
    team_id: 3,
    goals: 1,
    assists: 0,
  },
  {
    id: 10,
    game_id: 1,
    player_name: "Bradley Fitzpatrick",
    player_id: 40,
    team_id: 2,
    goals: 0,
    assists: 0,
  },
  {
    id: 11,
    game_id: 1,
    player_name: "Alex Vincent",
    player_id: 36,
    team_id: 2,
    goals: 0,
    assists: 0,
  },
  {
    id: 12,
    game_id: 1,
    player_name: "Dakota Summers",
    player_id: 33,
    team_id: 2,
    goals: 1,
    assists: 0,
  },
  {
    id: 13,
    game_id: 1,
    player_name: "Devin Burt",
    player_id: 39,
    team_id: 2,
    goals: 2,
    assists: 0,
  },
  {
    id: 14,
    game_id: 1,
    player_name: "Josh Dillon",
    player_id: 34,
    team_id: 2,
    goals: 1,
    assists: 0,
  },
  {
    id: 15,
    game_id: 1,
    player_name: "Brady Miller (A)",
    player_id: 29,
    team_id: 2,
    goals: 0,
    assists: 0,
  },
  {
    id: 16,
    game_id: 1,
    player_name: "Joel James",
    player_id: 31,
    team_id: 2,
    goals: 2,
    assists: 0,
  },
  {
    id: 17,
    game_id: 1,
    player_name: "Corey Normore",
    player_id: 32,
    team_id: 2,
    goals: 1,
    assists: 0,
  },
  {
    id: 18,
    game_id: 2,
    player_name: "Jack Hanlon",
    player_id: 72,
    team_id: 4,
    goals: 1,
    assists: 0,
  },
  {
    id: 19,
    game_id: 2,
    player_name: "Braden Skiffington",
    player_id: 68,
    team_id: 4,
    goals: 4,
    assists: 0,
  },
  {
    id: 20,
    game_id: 2,
    player_name: "Chase Barrett",
    player_id: 75,
    team_id: 4,
    goals: 1,
    assists: 0,
  },
  {
    id: 21,
    game_id: 2,
    player_name: "Mike Dwyer",
    player_id: 73,
    team_id: 4,
    goals: 1,
    assists: 0,
  },
  {
    id: 22,
    game_id: 2,
    player_name: "Mark Holloway",
    player_id: 69,
    team_id: 4,
    goals: 3,
    assists: 0,
  },
  {
    id: 23,
    game_id: 2,
    player_name: "Coady Bungay",
    player_id: 83,
    team_id: 4,
    goals: 0,
    assists: 0,
  },
  {
    id: 24,
    game_id: 2,
    player_name: "Nick Best",
    player_id: 70,
    team_id: 4,
    goals: 1,
    assists: 0,
  },
  {
    id: 25,
    game_id: 2,
    player_name: "Alex Smeall (C)",
    player_id: 1,
    team_id: 1,
    goals: 1,
    assists: 0,
  },
  {
    id: 26,
    game_id: 2,
    player_name: "Greg Abbott",
    player_id: 8,
    team_id: 1,
    goals: 0,
    assists: 0,
  },
  {
    id: 27,
    game_id: 2,
    player_name: "Steven Brewer",
    player_id: 9,
    team_id: 1,
    goals: 1,
    assists: 0,
  },
  {
    id: 28,
    game_id: 2,
    player_name: "Jason Duggan (A)",
    player_id: 2,
    team_id: 1,
    goals: 3,
    assists: 0,
  },
  {
    id: 29,
    game_id: 2,
    player_name: "Alan McDonald",
    player_id: 6,
    team_id: 1,
    goals: 0,
    assists: 0,
  },
  {
    id: 30,
    game_id: 2,
    player_name: "Liam Henebury",
    player_id: 7,
    team_id: 1,
    goals: 1,
    assists: 0,
  },
  {
    id: 31,
    game_id: 2,
    player_name: "Josh Shears",
    player_id: 4,
    team_id: 1,
    goals: 2,
    assists: 0,
  },
  {
    id: 33,
    game_id: 2,
    player_name: "Greg Thorne",
    player_id: 23,
    team_id: 1,
    goals: 1,
    assists: 0,
  },
];
